---
# tasks file for ansible-clamav
#

# Avoiding some error 
- name: fail if freshclam syslog and file log are defined in the same time
  fail:
     msg: "freshclam syslog and file log are defined in the same time. Choose one option"
  when: freshclam_log_file is defined and freshclam_log_syslog is defined
  tags: [ install, clamd, freshclam ]

- name: fail if clamd syslog and file log are defined in the same time
  fail:
     msg: "clamd syslog and file log are defined in the same time. Choose one option"
  when: clamd_log_file is defined and clamd_log_syslog is defined
  tags: [ install, clamd, freshclam ]  

# Installation
- name: install clamv packages
  yum:
    name: 
     - clamav-server 
     - clamav-data 
     - clamav-update 
     - clamav-filesystem 
     - clamav 
     - clamav-scanner-systemd 
     - clamav-devel 
     - clamav-lib 
     - clamav-server-systemd
    state: present
    enablerepo: "epel"
  tags: [ install, clamd, freshclam ]

# set selinux context for clamav
#  setsebool -P antivirus_can_scan_system 1 / setsebool -P clamd_use_jit 1
- name: Set antivirus_can_scan_system and antivirus_use_jit flag on and keep it persistent across reboot
  seboolean:
    name: "{{item}}"
    state: yes
    persistent: yes
  with_items:
   - antivirus_can_scan_system
   - antivirus_use_jit
  when: ansible_selinux.status == "enabled"
  tags: [ install, selinux, clamd, freshclam ]



