# tasks file for ansible-clamav

# some verification
- name: fail if freshclam syslog and file log are defined in the same time
  fail:
     msg: "freshclam syslog and file log are defined in the same time. Choose one option"
  when: freshclam_log_file is defined and freshclam_log_syslog is defined
  tags: [ install, clamd, freshclam ]

- name: fail if clamd syslog and file log are defined in the same time
  fail:
     msg: "clamd syslog and file log are defined in the same time. Choose one option"
  when: clamd_log_file is defined and clamd_log_syslog is defined
  tags: [ install, clamd, freshclam ]

# add epel repo
- name: Add Epel repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
  tags: [ install, epel ]

# update packages
- name: upgrade all packages, excluding kernel & some related packages
  yum:
    name: '*'
    state: latest
    #exclude: kernel*,security*
  when: update_pkg is defined and update_pkg
  tags: [ install, update ]

# Handler showing how to clean yum metadata cache
- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no
  tags: [ install, clean ]
