---
# tasks file for ansible-clamav
#

# Avoiding some error 
- name: fail if freshclam syslog and file log are defined in the same time
  fail:
     msg: "freshclam syslog and file log are defined in the same time. Choose one option"
  when: freshclam_log_file is defined and freshclam_log_syslog is defined
  tags: [ install, clamd, freshclam ]

- name: fail if clamd syslog and file log are defined in the same time
  fail:
     msg: "clamd syslog and file log are defined in the same time. Choose one option"
  when: clamd_log_file is defined and clamd_log_syslog is defined
  tags: [ install, clamd, freshclam ]  

- name: check if freshclam log rotation or logfile maxsize is correctily defined
  fail:
     msg: "freshclam log file must be defined with file maxsize or log rotation option"
  when: 
   - (freshclam_log_file_maxsize is defined or freshclam_log_rotate is defined)
   - freshclam_log_file is not defined
  tags: [ install, clamd, freshclam ]

- name: check if clamd log rotation or logfile maxsize is correctily defined 
  fail:
     msg: "clamd log file must be defined with file maxsize or log rotation option"
  when: 
   - (clamd_log_file_maxsize is defined or clamd_log_rotate is defined)
   - clamd_log_file is not defined
  tags: [ install, clamd, freshclam ]


