---
# handlers file for ansible-clamav

## start services
- name: start freshclam and clamd services
  systemd:
    name: "{{item}}"
    state: started
    daemon_reload: yes
    enabled: yes
  with_items:
   - clamav.freshclam
   - clamd@scan
  tags: service,start

## freshclam service restart
- name: restart freshclam
  systemd:
    name:  clamav.freshclam
    state: restarted

## clamd service restart
- name: restart clamd@scan
  systemd:
    name:  clamd@scan
    state: restarted
