---
# handlers file for ansible-clamav

## freshclam service restart
- name: restart freshclam
  systemd:
    name:  clamav.freshclam
    state: restarted

## clamd service restart
- name: restart clamd@scan
  systemd:
    name:  clamd@scan
    state: restarted
