---
# handlers file for ansible-clamav

## freshclam service (re)start
- name: restart freshclam
  systemd:
    name:  freshclam
    state: started

## clamd@scan service (re)start
- name: start clamd@scan
  systemd:
    name: clamd@scan
    state: restarted
    enabled: yes

- name: restart clamd@scan
  systemd:
    name:  clamd@scan
    state: restarted
