---
# handlers file for ansible-clamav

## freshclam service restart
- name: restart freshclam
  systemd:
    name:  freshclam
    state: restarted

## clamd service restart
- name: restart clamd
  systemd:
    name:  clamd
    state: restarted
